apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: default
  labels:
    app: client
spec:
  containers:
    - name: client
      image: docker.m.daocloud.io/library/busybox:1.38.0
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "sleep 36000"]
  restartPolicy: Never
